### ISSUE TITLE
Tune SVM 

### ISSUE THREAD

**Issue by WeiFoo** [ai-se/tunelearners#10]
# The tuner for SVM is done!
## ISSUES
-  some kernels provided by SckiKitLearn，like **linear** and **poly**, are way too slow, wait more than 10 minutes still running for even one single evaluation.. quit!!
-  **rbf** and **sigmoid** are running very fast
## Strategy
- tune key parameters for kernels **rbf**and **sigmoid**, respectively.

**Comment by timm** [comment]
i praise and hail the wisdom of my mighty graduate student

**Comment by WeiFoo** [comment]
# Tune SVM kernel sigmoid -- goal is F

## Charts

![62b26129-c359-4603-a6e8-feff182a7421](https://cloud.githubusercontent.com/assets/7039841/9123154/c0a5000c-3c5b-11e5-812b-9b79c7fae522.png)

## Observation

**sigmoid** kernel might not be appropriate  for this defect prediction because almost all F-value of naive learner are 0, but tuning still helps to improve its performance.

## Print outs

More details about results, check out #11

**Comment by WeiFoo** [comment]
# Tune SVM kernel rbf -- goal is F

## goal is F measure

## Charts

![6c0e5d91-41b7-4291-a635-e0bcea77ff3b](https://cloud.githubusercontent.com/assets/7039841/9123673/12fe051c-3c5f-11e5-8032-1e5c7e8025e4.png)

## Observation

Tuning helps!

## Print outs

More details about results, check out #12
