### ISSUE TITLE
we need a guidelines section

### ISSUE THREAD

**Issue by timm** [ai-se/tunelearners#13]
like section 5 of http://www.evosuite.org/wp-content/papercite-data/pdf/ssbse11_tuning.pdf

http://dl.acm.org/citation.cfm?id=2042252

```
@inproceedings{Arcuri:2011:PTS:2042243.2042252,
 author = {Arcuri, Andrea and Fraser, Gordon},
 title = {On Parameter Tuning in Search Based Software Engineering},
 booktitle = {Proceedings of the Third International Conference on Search Based Software Engineering},
 series = {SSBSE'11},
 year = {2011},
 isbn = {978-3-642-23715-7},
 location = {Szeged, Hungary},
 pages = {33--47},
 numpages = {15},
 url = {http://dl.acm.org/citation.cfm?id=2042243.2042252},
 acmid = {2042252},
 publisher = {Springer-Verlag},
 address = {Berlin, Heidelberg},
 keywords = {objectoriented, search based software engineering, test data generation, unit testing},
} 
```

**Comment by timm** [comment]
1. what is your summary of the Arcuir and Fraser guidelines?
2. if you rewrote those for our results, what would that look like?

to make space for that text  you could:
- turn some of dot lists to para text
- kill some orphan lines
- replace tables 8 and 9 witha  few histograms
-  reduce the y-axis sizes of figures 2,3,4

but lets see how much space you need. maybe you can squeeze into the end of p10

**Comment by WeiFoo** [comment]
The main point of Arcuir and Fraser's guideline is to use basic ML techniques to do tuning:
partition data into **training** and **test** data sets, and if it's small data set, use k-fold cross evaluation to do tuning.  and so forth...

here, in our paper, section 3.1, we explained how to split data sets and do tuning.
Also, those basic ML techniques are straightforward for folks in defect prediction filed using data mining tech, nothing new and they all should know those stuff.

if we do need to add some guidelines, I should come up with something new.

**Comment by timm** [comment]
so what is your call on why we use historical versioning rather than k-fold?

**Comment by WeiFoo** [comment]
K fold cross validation mixes up older and newer data, data from the future may be used to test on past data for tuning. 
and also we're not sure how much improvement k-fold will bring compared with our current version.
but one shortcoming is need more time

**Comment by WeiFoo** [comment]
added , need to revise

**Comment by timm** [comment]
i will reivse
