### ISSUE TITLE
naive_bayes and naive_logistic regression

### ISSUE THREAD

**Issue by WeiFoo** [ai-se/tunelearners#15]
# Compare untuned learners with NaiveBayes and logistic regression
## Observation
- Those **highlights** indicate the best score among untuned learners for each data set, **WHERE is not considered** 
- in terms of Precision, **logistic regression is indeed better than CART and RF**. but for F-measure, the advantage is not that big.
- Naive Bayes just doing fair.
- Tuning does help Cart or RF to compete with logistic regression in terms of precision.
## F

![8e321818-6251-4e24-9093-bf0006d57b5a](https://cloud.githubusercontent.com/assets/7039841/9209435/7ff93b94-4044-11e5-989b-89de21bcc8c4.png)
## Precision

![d14916aa-d5da-4c3e-9385-dce262f691d9](https://cloud.githubusercontent.com/assets/7039841/9209519/ed948ece-4044-11e5-9db0-83336ee643ff.png)

**Comment by WeiFoo** [comment]
# figs generated for paper

![8d838017-f762-4dab-9abf-5e9546bb8bdb](https://cloud.githubusercontent.com/assets/7039841/9233812/29fd7a42-4103-11e5-8910-c3fef28a2100.png)

**Comment by timm** [comment]
do we need both cart and random forest n the above? unless the rhetoric needs it, i'd stay with just RF. a case could be made that RF i s one the "more complex methods that generally dont do any better" (or some such..its something hall  said)

**Comment by WeiFoo** [comment]
Sure, agree with you and I wil remove CART.

**Comment by timm** [comment]
right. perfect example. hall argues that simpler methods like logistic often do better than more complex. and it can argued cerntainly  that RF is more complex (multiple models, need an additional operator to sumamrize conclusion over n trees, can look at the learned model, etc).

so untuned RF (the more complex) does worse than logistic. as hall says. medians are worse in 10 examples and better in none

but tuned RF, only worse in 5 examples and better in 8. which is consistent with our thesis. AND lots of people use logistic as their default learner.

**Comment by WeiFoo** [comment]
![4fb8b660-752d-4a75-96a6-22e3d542bc94](https://cloud.githubusercontent.com/assets/7039841/9261377/7fadd828-41db-11e5-8875-b167c1a94da2.png)

**Comment by timm** [comment]
v.nice
