### ISSUE TITLE
we need to defend the statement that "most data mining in analytics does not do tuning"

### ISSUE THREAD

**Issue by timm** [ai-se/tunelearners#16]
we need to defend the statement that "most data mining in analytics does not do tuning"

can you 
- [x] go to  https://goo.gl/LjvOkh
- [x] write down the citation counts of the top 50 papers
- [x] sort by those counts
- [x] discard the ones without pdf
- [x] discard the non SE papers
- [x] keep the top 30 survivors

for the surviving 30 papers, fire up in pdf. hunt for tuning, parameter, setting (anything else?) that might suggest they do tunings. also check validity section for any nervousness that their settings are not the wright ones?

| paperId | year | citations | mentions tuning at all? | does tuning? |
| --- | --- | --- | --- | --- |
| 1 | 1984 | 310 | n | n |

we need to defend the statement that "most data mining in analytics does not do tuning"

**Comment by WeiFoo** [comment]
paperId | year | citations | mentions tuning at all? | does tuning? | nervousness about settings|
-----------|--------|------------|--------------------------------|----------------- |-----|
1 | 1984 | 310  | n | n | n|

**Comment by timm** [comment]
k

**Comment by WeiFoo** [comment]
### ON GOOGLE SHEET
==>[LINK](
https://docs.google.com/spreadsheets/d/1K9oYjLtyZuXPAWTq2rfPGF5Zn4IWraPCPvVp_bXQFig/edit?usp=sharing)

**Comment by WeiFoo** [comment]
### Sorted In GOOGLE SHEET

Done! ==>[LINK](https://docs.google.com/spreadsheets/d/1K9oYjLtyZuXPAWTq2rfPGF5Zn4IWraPCPvVp_bXQFig/edit?usp=sharing)

**Comment by timm** [comment]
is that sheet public? please make it so.

also, plz add a second worksheet called "how we did it" as a title on the tab and text:

 In google scholar, search for "data mining" "software engineering" "defect prediction"
 Sort by citation
 Discard the ones without a  pdf
 Discard the non SE papers
 Keep the top 50 survivors
 Search for  tuning or parameter

**Comment by timm** [comment]
btw- great work on that sheet

**Comment by WeiFoo** [comment]
Done!
