### ISSUE TITLE
this is ... complicated

### ISSUE THREAD

**Issue by timm** [ai-se/tunelearners#19]
need to sleep on the following

note: DO NOT run off and do grid search based on this comment. this is "fyi.. we have to think on this"

there are some examples of tuning. grid search was used by lessmann et al and allamais et al

Miltiadis Allamanis, Earl T. Barr, Christian Bird, and Charles Sutton. 2014. Learning natural coding conventions. In Proceedings of the 22nd ACM SIGSOFT International Symposium on Foundations of Software Engineering (FSE 2014). ACM, New York, NY, USA, 281-293. DOI=10.1145/2635868.2635883 http://doi.acm.org/10.1145/2635868.2635883

fyi- grid search NOT recommended . 
@article{Bergstra12,
 author = {Bergstra, James and Bengio, Yoshua},
 title = {Random Search for Hyper-parameter Optimization},
 journal = {J. Mach. Learn. Res.},
 issue_date = {3/1/2012},
 volume = {13},
 month = feb,
 year = {2012},
 issn = {1532-4435},
 pages = {281--305},
 numpages = {25},
 url = {http://dl.acm.org/citation.cfm?id=2188385.2188395},
 acmid = {2188395},
 publisher = {JMLR.org},
 keywords = {deep learning, global optimization, model selection, neural networks, response surface modeling},
} 

this paper says:We~\cite{Bergstra12} have shown
that random experiments are more efficient than grid experiments for hyper-parameter optimization
in the case of several learning algorithms on several data sets. Our analysis of the hyper-parameter
response surface (Ψ) suggests that random experiments are more efficient because not all hyperparameters
are equally important to tune. Grid search experiments allocate too many trials to the
exploration of dimensions that do not matter and suffer from poor coverage in dimensions that are
important.XXX

**Comment by timm** [comment]
why did u repoen this? anything else needed?

**Comment by WeiFoo** [comment]
This shout be closed
