### ISSUE TITLE
repeated references

### ISSUE THREAD

**Issue by timm** [ai-se/tunelearners#21]
must remove them

**Comment by WeiFoo** [comment]
I removed those repeated ones.

one question:
we still have different formats for reference. say, for pages, we have the following two formats
- pages 1-11
- 2-13

and also, for some references we have **publisher**, others  not. Is there a strict format to follow?
even those published ICSE paper have different formats..

**Comment by timm** [comment]
scanned thru them all. none look stupid. reviewers will be fine as it is.
