### ISSUE TITLE
I'm not sure KS test in RQ3 is right or wrong

### ISSUE THREAD

**Issue by WeiFoo** [ai-se/tunelearners#25]
I added the KS results into RQ3, but what I did was pass those numbers from **tuned CART** and **Tuned RF** columns to do  KS test. is it right?

**Comment by timm** [comment]
cant see those results

and do you mean RQ3... which is about discrete values... or RQ4... which is about the numeric distributions of fig4.

and if you meanf fig4, are you saying that statistically, there is no difference in the curves shown in fig4, as determined by KS?

**Comment by WeiFoo** [comment]
In 4.2 section, the next to last paragraph. I added a sentence about KS test done on table 4, and 5

**Comment by timm** [comment]
what about the fig4 nums. are they insignificantly different?

**Comment by WeiFoo** [comment]
in fig4, 
if D value got from KS test greater than  1.36 x sqrt(34/(17*17)) = 0.46, we can reject  that two distributions are from the same distribution.i.e. they're different distributions.
- precision, CART with Where D= 0.4118, CART with RF D = 0.2941, RF with Where D = 0.1765
- F: Where with RF D = 0.2941, Where with CART D = 0.2352, RF with CART D = 0.2353.

According to these D's, we will say, they're all not significantly different from each other!

**Comment by timm** [comment]
what is the threshold for "different"?

**Comment by WeiFoo** [comment]
0.46

**Comment by timm** [comment]
Precc

|  | CART | RF | WHERE |
| --- | --- | --- | --- |
| CART |  | 0.29 | 0.42 |
| RF |  |  | 0.18 |
| WHERE |  |  |  |

F

|  | CART | RF | WHERE |
| --- | --- | --- | --- |
| CART |  | 0.24 | 0.24 |
| RF |  |  | 0.29 |
| WHERE |  |  |  |

**Comment by timm** [comment]
can you add the above tables to the paper

**Comment by WeiFoo** [comment]
Sure,  I will do it.

**Comment by WeiFoo** [comment]
added! right below  fig.4

![60d7a186-4af7-4d63-ba4b-06261d76c7f6](https://cloud.githubusercontent.com/assets/7039841/9368472/7c0b2d6e-4691-11e5-80a1-03a63122d65c.png)

**Comment by WeiFoo** [comment]
```
This observation is supported by the KS results of Table 7.
At a 95% confidence, the KS thresh- old is 1.36􏰃34/(17 ∗ 17) = 0.46 
which is greater than the values in Figure 4.
That is, no result in Figure 4 is significantly different to any 
other– which is to say that there is no evidence that np=10
 is a poor choice of search space size.
```

Here we do KS on improvements of different learners, our conclusion is
 **no result in Figure 4 is significantly different to any other**

 Do we need to do KS test on results of each learner with np = 10 and recommended np?
then the conclusion would be **for each learner, tuning with np = 10 is no significantly different to any recommended np's**?

To me, the above two conclusions are slightly  different.

**Comment by timm** [comment]
i thought your treatments were 

np=10 vs np=EvertthingElse

if so, our current results are fine.

but please advise

**Comment by vivekaxl** [comment]
@timm : please take care of this

**Comment by vivekaxl** [comment]
#1
