### ISSUE TITLE
x-axis for all figures not clear!

### ISSUE THREAD

**Issue by WeiFoo** [ai-se/tunelearners#29]
### x-axis for fig 2,3,4,5 should be the same and consistent, but current are different.

Here're my options:
- data sets, sorted
- experiments, sorted

Please advise!!

![7efa91de-09bb-4da8-ba01-3423b5ab7c36](https://cloud.githubusercontent.com/assets/7039841/9399007/3a91a822-477c-11e5-9f4c-f87576b27a66.png)

![e8fb7b21-6bac-4dd6-9a6c-105650276318](https://cloud.githubusercontent.com/assets/7039841/9399012/52475732-477c-11e5-9aa3-cba9fbee0151.png)

![41403f0f-0b24-4d44-8699-8bf64ea81ab0](https://cloud.githubusercontent.com/assets/7039841/9399017/5e7ea064-477c-11e5-9e5d-94c4fc950a56.png)

![8f93b8c4-89de-4ae1-84eb-36ce67f8407e](https://cloud.githubusercontent.com/assets/7039841/9399020/6ef1b1b6-477c-11e5-9668-e41e82c43532.png)

**Comment by timm** [comment]
er... data sets sorted?

**Comment by WeiFoo** [comment]
Done
