### ISSUE TITLE
np = 90 and the tuning goal is F

### ISSUE THREAD

**Issue by WeiFoo** [ai-se/tunelearners#7]
## Conclusion
- **Our statement still holds that np = 10 is enough!**
- need an appropriate format to show this not the following chart. probably the delta figure in the paper we used.
## Tune WHERE with np = 90 and np = 10

![6343b00e-37f7-4296-bda3-e123ab24a10c](https://cloud.githubusercontent.com/assets/7039841/9090727/f6b206ba-3b69-11e5-8237-59227b265250.png)
## Tune CART with np = 90 and np = 10

![8a903da1-31e0-4494-add6-7af6393ea9c4](https://cloud.githubusercontent.com/assets/7039841/9090740/10e0d692-3b6a-11e5-96d2-a236089ea5eb.png)
## Tune RF with np = 90 and np = 10

![82794d4d-a851-47af-abeb-74fa3c45af33](https://cloud.githubusercontent.com/assets/7039841/9090781/3ccb80ea-3b6a-11e5-858e-7b17f5044a63.png)

**Comment by WeiFoo** [comment]
## Raw results -- > #14

**Comment by timm** [comment]
from the above charts, i see that sometimes np=10 does BETTER than np=90. 

what is the extra information in the ascii text... i dont want to miss any major point

now its time to think how to report all this succinctly... summary in the paper and large charts on-line?

**Comment by WeiFoo** [comment]
a chart for this #9
