### ISSUE TITLE
a new chart for those features selected..

### ISSUE THREAD

**Issue by WeiFoo** [ai-se/tunelearners#8]

**Comment by WeiFoo** [comment]
## Strategy

Select 4 parameters from WHERE and sort values. all the other parameters can be found in the supporting table -->[HERE](https://github.com/ai-se/tunelearners/blob/master/support%20results/support.pdf)

![51d260f5-d182-4fb4-97ee-bb7678c54029](https://cloud.githubusercontent.com/assets/7039841/9147265/ab3ddc98-3d32-11e5-83eb-cdebc078fb9a.png)

**Comment by WeiFoo** [comment]
Done!

**Comment by timm** [comment]
Nice. Much shorter that those ugly tables
