### ISSUE TITLE
a chart for np = 10 and np = 90

### ISSUE THREAD

**Issue by WeiFoo** [ai-se/tunelearners#9]
![55c4d958-2dcc-4ef0-87aa-204ebf5fcb20](https://cloud.githubusercontent.com/assets/7039841/9144860/f1ef82be-3d1d-11e5-9aef-364151211682.png)

**Comment by WeiFoo** [comment]
Done!

**Comment by timm** [comment]
this figure has a different axis to the #7 charts. what 2 figures are you proposing for the paper?

**Comment by WeiFoo** [comment]
actually, this figure is the combination of only the improvement in each figure of #7. I will run another experiment with np = 90 for **precision** to make two figures for the paper

**Comment by WeiFoo** [comment]
## Updates:
1. instead of using np=90 for all WHRE, CART and RF to compare with np = 10, **I use np=90,50,60 for WHERE, CART and RF, respectively, which are the recommended numbers by Storn**. I think results from these numbers will be more convincing .
2. tune learners over **F** and **precision**, the following charts are deltas between np = 10 and those recommended numbers.

![fbb8d385-1a81-4d72-8e7f-ff4b13b87fc0](https://cloud.githubusercontent.com/assets/7039841/9156498/17afc170-3eaa-11e5-9470-1a2c22e35b58.png)

**Comment by timm** [comment]
finding it hard to read this... not yet seeing, at a glance, the relative metrics of np 10,50,60,90 for 3 learners over n data sets... i guess that is coming?

**Comment by WeiFoo** [comment]
Each curve here:

WHERE: improvements of np = 90 over np = 10
CART : improvements of np = 50 over np = 10
RF : improvements of np = 60 over np = 10

**Comment by timm** [comment]
so lets change that legend...

**Comment by WeiFoo** [comment]
# Data sets that improved over np = 10

The dataset has been arranged in a descending order of improvement for instance xercesV1 improved more than jeditV0.

## Precision:
- WHERE: xercesV1, jeditV0, xercesV0
- CART:xercesV1, velocity, jeditV0, lucene, xercesV0, ivy, camelV0, poiV0, jeditV1,
- RF: xercesV1, jeditV0, velocity, jeditV1, xercesV0

## F:
- WHERE: jeditV2, antV1, synapse, antV0, xercesV1, antV2, velocity, ivy,
- CART: camelV0, ivy, jeditV0, poiV0,velocity,synapse,jeditV2,antV2,
- RF: antV2,velocity,xercesV0, synapse,jeditV2,camelV1,
